In [62]:
import numpy as np
import pandas as pd

In [63]:
def getDataFromFile(filename):
    
    f = open(filename , 'r')
    X = f.readlines()
    X = np.array(X)
    return X

In [64]:
XTrainingDataFileName = "/Volumes/part3/IMDB_Dataset/StemmedReviews_Xtrain.txt"
XTestingDataFileName = "/Volumes/part3/IMDB_Dataset/StemmedReviews_Xtest.txt"

YTrainingDataFileName = "/Volumes/part3/IMDB_Dataset/imdb_trainY.txt"
YTestingDataFileName = "/Volumes/part3/IMDB_Dataset/imdb_testY.txt"

In [65]:
Xtrain = getDataFromFile(XTrainingDataFileName)
print(Xtrain.shape)

(25000,)


In [66]:
Xtest = getDataFromFile(XTestingDataFileName)
print(Xtest.shape)

(25000,)


In [69]:
Ytrain = getDataFromFile(YTrainingDataFileName)
print(Ytrain.shape)
Ytrain = Ytrain[1:]
print(Ytrain.shape)

Ytest = getDataFromFile(YTestingDataFileName)
print(Ytest.shape)


(25001,)
(25000,)
(25000,)


In [71]:
def CleanYData(Y):
    for i in range(Y.shape[0]):
        Y = Y.astype(np.int)
        
    return Y

In [73]:
Ytrain = CleanYData(Ytrain)
Ytest = CleanYData(Ytest)

In [75]:
print(Ytrain[:6])
print(Ytest[:6])
print(type(Ytrain))
print(type(Ytest))

[ 8  7  8  8  8 10]
[ 7 10 10 10  8 10]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [94]:
Xtrain[0].split(' ')

['love',
 'movi',
 'sinc',
 '7',
 'saw',
 'open',
 'day',
 'touch',
 'beauti',
 'strongli',
 'recommend',
 'see',
 'movi',
 'watch',
 'famili',
 'far',
 'mpaa',
 'rate',
 'pg',
 '13',
 'themat',
 'element',
 'prolong',
 'scene',
 'disastor',
 'nuditi',
 'sexual',
 'languag\n']

In [79]:
from sklearn.feature_extraction.text import CountVectorizer

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
